# Generated by Django 4.1.3 on 2023-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='urlmodel',
            name='url_id',
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='key_url',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='urlmodel',
            name='value_url',
            field=models.CharField(default='admin\\', max_length=50),
        ),
    ]
