# Generated by Django 4.1.3 on 2023-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0002_remove_urlmodel_url_remove_urlmodel_url_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='key_url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='value_url',
            field=models.CharField(max_length=50),
        ),
    ]
